# Generated by Django 3.2 on 2024-04-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.CharField(default='@', max_length=100),
            preserve_default=False,
        ),
    ]
