# Generated by Django 3.2 on 2024-04-13 21:06

from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pessoa_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='dataNasc',
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='paisDesejado',
            field=models.CharField(default='indefinido', max_length=52),
            preserve_default=False,
        ),
    ]
